#!bin/sh
#

cmd=$(which tmux)
session=$(hostname -s)

if [ -z $cmd ]; then
    echo "You should install tmux."
    exit 1
fi

$cmd has -t $session 2> /dev/null

if [ $? != 0 ]; then
    $cmd new -d -n vim -s $session "vim"
     $cmd neww -n irssi -t $session "irssi"
    $cmd neww -n cmus -t $session "cmus"
    $cmd neww -n zsh -t $session "zsh"
    #$cmd splitw -h -p 50 -t $session "zsh"
    $cmd selectw -t $session:4
fi

$cmd att -t $session

exit 0
